distribution_code_name: Weasel
distribution_name: "小狼毫"
distribution_version: 0.15.0.0
install_time: "Sat Oct 28 03:14:52 2023"
rime_version: 1.8.5
sync_dir: 'C:\Users\gendloop-work\Desktop\BaiduSyncdisk\Rime'
installation_id: 'gendloop-rime-config'